name: rabbit
on:
  push:
    branches:
      - master

jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           java-version: 21
#           distribution: temurin
#           cache: gradle
#       - name: Pemission
#         run: chmod +x ./gradlew
#       - name: Build with Gradle
#         run: ./gradlew clean build
